substitutions:
  name: ikea-vindriktning
  friendly_name: "IKEA Vindriktning"
  log_level: DEBUG

esp8266:
  board: d1_mini

uart:
  rx_pin: D1
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"

packages:
  base: !include common/device-base.yaml
  ota:  !include common/ota-http-request-proxy.yaml