substitutions:
  name: ikea-vindriktning
  friendly_name: "IKEA Vindriktning"
  log_level: DEBUG

esp8266:
  board: d1_mini

# Fix for ESPHome builds failing for missing tx_pin
# https://github.com/esphome/esphome/pull/12529
external_components:
  - source: github://pr#12529
    components: [pm1006]
    refresh: 1h

uart:
  rx_pin: D1
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"

packages:
  base: !include common/device-base.yaml
  ota:  !include esp8266/ota-http-request.yaml