substitutions:
  name: pet-sprayer
  friendly_name: "Pet Sprayer"
  log_level: DEBUG

esp8266:
  board: esp01_1m

switch:
  - platform: gpio
    pin: GPIO3
    name: "Trigger"
    id: trigger
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: trigger

# MQTT Configuration for easy/legacy integration with Blue Iris alert triggers.
mqtt:
  broker: !secret mqtt_hostname
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  on_message:
    - topic: sprayer/command
      payload: "fire"
      then:
        - switch.turn_on: trigger

packages:
  base: !include common/device-base.yaml
  ota:  !include esp8266/ota-http-request.yaml