esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: "sdwagner2615.esphome-configurations"
    # The following version number will have the version of ESPHome appended to it
    # when the build is run. ie: "1.0-2025.07.05"
    version: "0.13"

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:

# Supported OTA update methods
ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ap:

captive_portal:

web_server:
  port: 80

button:
  - platform: safe_mode
    name: Restart (Safe Mode)
  - platform: restart
    name: Restart
  - platform: factory_reset
    name: Factory Reset

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s